# Configuration file for testing novel view synthesis on training set (see paper section 4, paragraph 4)
# Datasets can be downloaded here: https://drive.google.com/drive/folders/1OkYgeRcIcLOFu1ft5mRODWNQaPJ0ps90

# data_root: /eva_data/psa/datasets/srn_data/cars_train_test/ # Path to cars training_test set (cars from training set with novel views).
data_root: /eva_data/psa/NVS/datasets/ShapeNet.v2_128/airplane_car_chair_train # Path to cars training dataset.
logging_root: ./logs/shapenet.v2_airplane_car_chair_200/test_3d         # one_shot_cars_new_RandomView_MV4_test4views_iter100000
num_instances: 600 # The number of cars that the model was trained with.
checkpoint: /eva_data/psa/NVS/code/scene-representation-networks/logs/shapenet.v2_airplane_car_chair_200/checkpoints/epoch_0019_iter_140000.pth # The path to the trained checkpoint
# checkpoint: /work/eva0856121/code/outputs/srn_new_RandomView_MV4/checkpoints/epoch_0012_iter_100000.pth # The path to the trained checkpoint
img_sidelength: 128
batch_size: 16 # This is for a GPU with 48 GB of memory. Adapt accordingly for your GPU memory.
